_target_: pyggnn.model.SchNet
node_dim: 256
edge_filter_dim: 256
n_conv_layer: 6
out_dim: 1
n_gaussian: 64
activation: "shifted_softplus"
cutoff_net: null # TODO: add cosing cutoff nn.module
cutoff_radi: ${params.cutoff_radi}
hidden_dim: 256
aggr: "add"
scaler: null
mean: null
stddev: null
weight_init: "xavier_uniform_"
share_weight: false
max_z: 100