# @package _global_

defaults:
  - data: data
  - model: dimenetpp
  - optimizer: adam
  - scheduler: cosine_annealing  # nullable
  - loss_fn: rmse
  - plmodule: gnn_module
  - callbacks:
      - early_stopping
      - lr_monitor
  - loggers: 
      - csv
      - tensorboard
  - trainer: default_trainer_gpu

configs:
  job_name: "dimenetpp"
  gpus: 1
  num_workers: 4
  prediction_key: "formation_energy"

training:
  amp_level: null  # nullable
  seed: 42
  batch_size: 32
  max_epochs: 1000
  lr: 0.001
  weight_decay: 0.0
