version: "3.8"

services:
  train:
    build:
      context: ../
      dockerfile: ./Dockerfile
    runtime: nvidia
    volumes:
      - type: volume
        source: data
        target: /data
      - type: volume
        source: logs
        target: /logs
    env_file:
      - .env

volumes:
  data:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.106,rw"
      device: ":/home/nishio/data"
  logs:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.106,rw"
      device: ":/home/nishio/logs"
