FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

RUN conda install -c conda-forge \
    numpy=1.23.5 \
    scipy=1.10.1 \
    sympy=1.11.1 \
    ase=3.22.1 \
    pymatgen=2022.4.19 \
    pytorch-lightning=2.0.0 \
    && \
    conda install -c pyg \
    pyg \
    pytorch-scatter \
    pytorch-sparse \
    && \
    conda clean --all -y

ENTRYPOINT [ "/bin/bash", "-c" ]
