FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

RUN conda install -c conda-forge \
    numpy=1.23.5 \
    scipy=1.10.1 \
    sympy=1.11.1 \
    ase=3.22.1 \
    pymatgen=2022.4.19 \
    pytorch-lightning=2.0.0 \
    && \
    conda install pyg -c pyg \
    && \
    conda clean --all -y

ENTRYPOINT [ "/bin/bash", "-c" ]
