package:
  name: lcaonet
  version: 1.2.0

source:
  url: https://github.com/nmdl-mizo/lcaonet/archive/refs/tags/v1.2.0.tar.gz
  git_url: https://github.com/nmdl-mizo/lcaonet
  git_rev: 1.2.0
  git_depth: -1

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - sympy
    - ase
    - pymatgen
    - torch
    - torch_geometric
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install .

test:
  imports:
    - lcaonet
    - lcaonet.atomistic
    - lcaonet.data
    - lcaonet.model
    - lcaonet.nn
    - lcaonet.train
    - lcaonet.utils

about:
  home: https://github.com/nmdl-mizo/lcaonet
  license: MIT
  summary: GCNN including orbital interaction, physically motivatied by the LCAO method.
