package:
  name: lcaonet
  version: 1.2.0

source:
  path: ../

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - sympy
    - ase
    - pymatgen
    - pytorch
    - pyg

test:
  imports:
    - lcaonet
    - lcaonet.atomistic
    - lcaonet.data
    - lcaonet.model
    - lcaonet.nn
    - lcaonet.train
    - lcaonet.utils

about:
  home: https://github.com/nmdl-mizo/lcaonet
  readme: README.md
  license: MIT
  license_file: LICENSE
  summary: GCNN including orbital interaction, physically motivatied by the LCAO method.
