package:
  name: lcaonet
  version: 1.2.0

source:
  path: ../

requirements:
  host:
    - python >=3.7
    - pip >=18.0
    - numpy >=1.17

  run:
    - python >=3.7
    - numpy >=1.17
    - scipy ==1.10.1
    - sympy ==1.11.1
    - ase ==3.22.1
    - pymatgen ==2022.4.19
    - pytorch ==2.0.0
    - pyg

build:
  script: pip install .

test:
  imports:
    - lcaonet
    - lcaonet.atomistic
    - lcaonet.data
    - lcaonet.model
    - lcaonet.nn
    - lcaonet.train
    - lcaonet.utils

about:
  home: https://github.com/nmdl-mizo/lcaonet
  license: MIT
  summary: GCNN including orbital interaction, physically motivatied by the LCAO method.
