package:
  name: lcaonet
  version: 1.2.0

source:
  path: ../

requirements:
  host:
    - python >=3.7
    - pip >=18.0

  run:
    - python >=3.7
    - numpy
    - scipy
    - sympy
    - ase
    - pymatgen
    - pytorch
    - pyg

build:
  script: pip install .

test:
  imports:
    - lcaonet
    - lcaonet.atomistic
    - lcaonet.data
    - lcaonet.model
    - lcaonet.nn
    - lcaonet.train
    - lcaonet.utils

about:
  home: https://github.com/nmdl-mizo/lcaonet
  license: MIT
  summary: GCNN including orbital interaction, physically motivatied by the LCAO method.
