package:
  name: lcaonet
  version: 1.2.0

source:
  git_url: https://github.com/nmdl-mizo/lcaonet
  git_rev: 1.2.0
  git_depth: -1

requirements:
  host:
    - python
    - pip

  run:
    - python

build:
  script: pip install .

test:
  imports:
    - lcaonet
    - lcaonet.atomistic
    - lcaonet.data
    - lcaonet.model
    - lcaonet.nn
    - lcaonet.train
    - lcaonet.utils

about:
  home: https://github.com/nmdl-mizo/lcaonet
  license: MIT
  summary: GCNN including orbital interaction, physically motivatied by the LCAO method.
