package:
  name: lcaonet
  version: 1.4.0

source:
  path: ../

requirements:
  host:
    - python
    - pip >=18.0

  run:
    - python
    - numpy
    - scipy
    - sympy
    - ase
    - pytorch
    - pyg
    - pytorch-scatter
    - pytorch-sparse

build:
  script: pip install .

test:
  imports:
    - lcaonet
    - lcaonet.atomistic
    - lcaonet.data
    - lcaonet.model
    - lcaonet.nn
    - lcaonet.train
    - lcaonet.utils

about:
  home: https://github.com/nmdl-mizo/lcaonet
  license: MIT
  summary: LCAONet - MPNN including orbital interaction, physically motivatied by the LCAO method.
