_target_: pytorch_lightning.Trainer

# device settings
devices: ${configs.gpus}
accelerator: "gpu"

# training settings
min_epochs: null
max_epochs: ${training.max_epochs}

# other settings are same as defaults
enable_model_summary: True
profiler: null

gradient_clip_val: 0
accumulate_grad_batches: 1
val_check_interval: 1.0
check_val_every_n_epoch: 1

num_sanity_val_steps: 0
fast_dev_run: False
overfit_batches: 0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
track_grad_norm: -1
detect_anomaly: False

amp_backend: "native"
amp_level: ${training.amp_level}
precision: 32
num_nodes: 1
tpu_cores: null
deterministic: False

resume_from_checkpoint: null