name: CI with unittest and formatting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Formatting with Black
      uses: psf/black@stable
      with:
        options: "--check --verbose --diff -l 120"
        src: "./src/pyggnn"
        version: "21.5b1"

    - name: Install pyggnn
      run: |
        pip install -e .
    
    - name: Unittest
      run: |
        python -m unittest discover -s tests -p "test_*.py"
